### ISSUE TITLE
Allow 'stack' parameter

### ISSUE THREAD

**Issue by iross** [UW-COSMOS/cosmos-visualizer#12]
Would be nice to be able to pull (or filter) results based on what pile of ingested documents they come from (the 'stack' column).

**Comment by davenquinn** [comment]
This actually uses the `stack_id` column in the `image_stack` table. So we really should standardize on `stack_id` to refer to this where possible. Right now the API translates `stack_id` to `stack` for consumption by the frontend. The frontend uses `stack` in some cases and `stack_id` in others, which has caused several bugs.

**Comment by iross** [comment]
Oof, yeah. I've always been bad at this kind of consistency. I'm pretty
sure I call it `stack_name` in a number of places as well.
