### ISSUE TITLE
access control origin checks preventing linking gdd/api to kb results

### ISSUE THREAD

**Issue by cambro** [UW-COSMOS/cosmos-visualizer#14]
Safari's default is preventing any display of GDD linked results due to access control checks:

```[Error] XMLHttpRequest cannot load http://geodeepdive.org/api/articles?docid=54b43248e138239d86849d0a due to access control checks.```

```.../articles?docid=54b43248e138239d86849d0a denied by Cross-Origin Resource Sharing policy: Origin http://birdnest.geology.wisc.edu is not allowed by Access-Control-Allow-Origin.```

**Comment by davenquinn** [comment]
Seems like this is a GDD-side problem? I don't know how to get around access-control from the client, but maybe I'm not in the know. @iross?

**Comment by iross** [comment]
Ahhh, good call.

Added:
```
add_header Access-Control-Allow-Origin birdnest.geology.wisc.edu;
```
...to the nginx config serving the API and it looks to be working now.

**Comment by cambro** [comment]
This issue is not resolved. same Access-Control-Allow-Origin issue.

**Comment by cambro** [comment]
Maybe this tag? check it out. low priority.
https://stackoverflow.com/questions/16824661/cors-request-not-working-in-safari

**Comment by davenquinn** [comment]
Seems to have been resolved by newer updates to the apps...
