### ISSUE TITLE
"Internal-only" mode support

### ISSUE THREAD

**Issue by iross** [UW-COSMOS/cosmos-visualizer#21]
Request from Theo -- an internally-accessible setup that has a better way of viewing full documents (e.g. remove randomness, add a feature for selecting a document/page/etc.)

**Comment by cambro** [comment]
Ideally we would implement this as an environment variable. This environment variable could have three levels:
- public: (random full pages, i.e., the current mode)
- public limited: no full pages (only model and kb views)
- dev: docs selected, full pages sequentially shown for whole doc
