### ISSUE TITLE
JSON objects returned via API missing reference data

### ISSUE THREAD

**Issue by cambro** [UW-COSMOS/cosmos-visualizer#35]
We previously did this exactly right:
http://birdnest.geology.wisc.edu/cosmos_enriched_tables/search?id=5dd3151e9878524fb7aebdaf

Now, we do not do it right:
http://cosmos3.chtc.wisc.edu:8081/search?id=88914

Everything that leaves xDD and is exposed anywhere must carry along the full citation data and link back original source. 

I realize this is likely an API-side change, but use in the visualizer which we are making public requires this to be priority, either dropped from interface or fixed API side.

**Comment by davenquinn** [comment]
I assume this is easy to fix on the API side but am willing to drop it from the frontend if needed. Generally, what we used to do is largely irrelevant because the entire API codebase has been replaced.

**Comment by cambro** [comment]
We really want this in the front end. The COMPLETE data object we have for each fig/table etc. with its citation.

**Comment by cambro** [comment]
Small side note @iross to think about. right now looks like the id is a straight digit from DB. that's ok, but a hash of some kind would be better. Otherwise, anyone could write an API-thrashing script to scrape everything we have exposed with basically zero effort....

**Comment by iross** [comment]
Yeah I'll bring this back ASAP.

Very good point on the IDs. I had on the list of things to do but just ran out of time.. 

I'm going to open up issues for this over in the COSMOS repo.

**Comment by iross** [comment]
Resolved via https://github.com/UW-COSMOS/Cosmos/commit/a12a5d9b86ccc6661d30ca04b80aa8c8fda24526
