### ISSUE TITLE
OCR text button leads to empty target=_blank

### ISSUE THREAD

**Issue by cambro** [UW-COSMOS/cosmos-visualizer#36]
directs new window to about:blank

**Comment by davenquinn** [comment]
which browser? in FF and Safari, it opens a new window pointed at the "data url" containing text. I can change it back to downloading that file instead, but I like it showing up in the browser where possible.

**Comment by cambro** [comment]
this was in Chrome

**Comment by davenquinn** [comment]
OK. Can't replicate until the backend is returned to us, sadly.

**Comment by davenquinn** [comment]
OK. Chrome apparently [switched to not open data URLs in-browser](https://stackoverflow.com/questions/46818033/opening-datatext-plain-window-in-chrome-showing-up-blank) for some reason. So we're going to switch back to downloading a plain text file across the board. Somewhat more tedious to view the content, but apparently less breakable.
