### ISSUE TITLE
intermittent image load failure

### ISSUE THREAD

**Issue by cambro** [UW-COSMOS/cosmos-visualizer#37]
It is common to conduct a search and then have images fail to load in the browser (confirmed in Safari). See image below. Refreshing the page loads the images. 
<img width="829" alt="blanks" src="https://user-images.githubusercontent.com/6107153/78575189-a017eb80-77f0-11ea-9802-3696a3831892.png">

**Comment by davenquinn** [comment]
Any particular search interaction you have to do prior? I am not currently replicating.

**Comment by davenquinn** [comment]
Aha just did.

**Comment by davenquinn** [comment]
Pixel width and height for images are calculated in JS after load so they can be displayed the proper size. Something about the resizing code isn't running in all circumstances, so the width/height of the images fall back to zero.
