### ISSUE TITLE
expand related terms list via target='_blank' link

### ISSUE THREAD

**Issue by cambro** [UW-COSMOS/cosmos-visualizer#38]
Would be very helpful to allow users to expand the related terms list and see correlation coefficients. I would implement this for now as a link to new window with just the plain JSON object, but with n parameter set to 50.

**Comment by davenquinn** [comment]
would it be useful to also show coefficients by default?

**Comment by cambro** [comment]
Maybe? Small text, round to 3 sig figs if you want to try it
