### ISSUE TITLE
Invalid API response from toggling size constraint on-off with ES

### ISSUE THREAD

**Issue by cambro** [UW-COSMOS/cosmos-visualizer#40]
To reproduce:

Do search.
Open details.
Select ElasticSearch 
Toggle on then off size constraint

<img width="565" alt="bug" src="https://user-images.githubusercontent.com/6107153/78831066-a05de580-79ae-11ea-93b9-1215bac01c5e.png">

**Comment by davenquinn** [comment]
Yeah this is due to a major update to the API that @iross  just pushed out. We significantly changed a few structures within the response. I am working on the update now.
