### ISSUE TITLE
don't give nuke option for related terms, instead "collapse/expand list"

### ISSUE THREAD

**Issue by cambro** [UW-COSMOS/cosmos-visualizer#44]
If a user clicks the red x on related terms, that interface element is no longer accessible to the user, even on a new search (though it does seem to pop back sometimes?). In order to retrieve it, the page must be reloaded.

Replace red x with collapse/expand similar to "show details"

**Comment by davenquinn** [comment]
Clicking on the list/hamburger button off to the side will bring it back, as will scrolling to the top of the list. This isn’t particularly obvious though, clearly. Maybe adding “terms” or equivalent text would help?

**Comment by cambro** [comment]
Ah, I see!  This is not important, then.
