### ISSUE TITLE
Nothing returned immediately in ES search seems wrong

### ISSUE THREAD

**Issue by cambro** [UW-COSMOS/cosmos-visualizer#48]
https://cosmos.wisc.edu/sets/covid/?backend=ElasticSearch&query=IC50%20Remdesivir&type=Table

**Comment by cambro** [comment]
Here is a table that should be retrieved regardless of how handled by ES:
http://cosmos3.chtc.wisc.edu:8081/search?id=3067709

**Comment by davenquinn** [comment]
This is a backend error apparently, an empty response is returned from the API. @iross ?
