### ISSUE TITLE
Display text content for each object

### ISSUE THREAD

**Issue by ankur-gos** [UW-COSMOS/cosmos-visualizer#54]
Currently, only the associated images are displayed in the interface. The text returned with the object should also be returned and displayed, especially for equation objects.

Since the api does not return images for figure captions, table captions, and text sections anymore, it's also important for other objects.

**Comment by davenquinn** [comment]
Sometimes we may want to show both, or show the image only. Examples would be figures and tables, especially, where the text layer may be just noise. Or in situations where the text layer is pulled from OCR, it might be preferable to show the visual extraction even for body text.

Could the API provide an indication of which display it prefers for each extraction? That way the visualizer could handle this in a nuanced way.

**Comment by ankur-gos** [comment]
In the new API OCR is a fall back, and most documents have a nice text layer, especially PDFs pulled from biorxiv, etc. The quality of the text coming back is much, much better as a result. Before we always OCRd the document.

We can mark whether the content returned is via OCR in case you don't want to display text if it comes from OCR.

We don't keep images of figure captions/table captions anymore, so the only option there is to just not display the text.
