### ISSUE TITLE
Make permalink button open new tab/window

### ISSUE THREAD

**Issue by cambro** [UW-COSMOS/cosmos-visualizer#62]
Currently if a user has scrolled through several pages of results and then clicks permalink button it is necessary to hit the back button to return to search, but doing so returns you to top of search scroll and resets all thresholds to defaults. This is disruptive and prevents scrolling through multiple results and assembling collection of links.

**Comment by cambro** [comment]
Note that this also greatly increase load on server API because it prompts user to fast scroll down to catch up. So +1 for this as a priority in the search interface.

**Comment by davenquinn** [comment]
Yes, adding a `_target=blank` will fix this

**Comment by davenquinn** [comment]
We should also add some sort of paging cursor to the url maybe...

**Comment by cambro** [comment]
> Yes, adding a `_target=blank` will fix this

Would be good to implement this. It is a real impediment to finding and flagging bad extractions./

**Comment by davenquinn** [comment]
Hmm, thought I fixed this pretty immediately. I think it’s in the latest `xdddev` branches (which is currently non-functional due to API maybe?) but not pushed to production.

Daven
