### ISSUE TITLE
Check that scrolling goes all the way to N pages (and doesn't stop arbitrarily)

### ISSUE THREAD

**Issue by cambro** [UW-COSMOS/cosmos-visualizer#66]
Example:
https://xdd.wisc.edu/set_visualizer/sets/dolomites?query=thin%20section&type=Figure

This reports 9 pages. It allows you to scroll down to hit "2 of 9" and then "3 of 9" but then there is no more after that. Not sure where bug lies, either in counting of scrolls or estimation of the "of 9" part.

**Comment by davenquinn** [comment]
For me, that seems to load more than three pages just fine, although for some reason it's showing "0" as the total count of pages for whatever reason...

**Comment by davenquinn** [comment]
I suspect that this was some sort of backend issue; I am unable to replicate on the frontend. It seems like there are now 46 pages of results, but _sometimes_ the total count is shown as "0" pages rather than "46". This doesn't appear to affect loading of successive pages though.
