### ISSUE TITLE
Make the default word2vec model adjustable 

### ISSUE THREAD

**Issue by iross** [UW-COSMOS/cosmos-visualizer#73]
For some sets, it may make more sense to retain capitalization when doing the related term word2vec lookup. Right now the visualizer is hardcoded to use the lowercase + ligature-cleaned model by default:

https://github.com/UW-COSMOS/cosmos-visualizer/blob/bdcbe1da4bb9bcff8cdf99ea5b95254f7c512f3d/frontend-shared/src/visualizer-app/knowledge-base/related-terms.ts#L48

Ideally this would be easily changeable.

**Comment by cambro** [comment]
seems like this one has been handled nicely.
