### ISSUE TITLE
consistent handling of multiple terms

### ISSUE THREAD

**Issue by cambro** [UW-COSMOS/cosmos-visualizer#75]
Comma-separated terms seem to be handled correctly for object retrieval but are not handled gracefully for embedding model. Would be good to double check how this is handled and allow multiple terms searches for retrieval and smart parsing of those for embedding model. "hard coded" comma separation would probably be fine.

Example:
https://xdd.wisc.edu/set_visualizer/sets/dolomites?query=dolomite%2Cthin%20section&type=Figure

**Comment by iross** [comment]
In addition to the embedding model interface, there's some issues with utilizing multiple terms via a direct URL. Collaborators want to be able to send their users to our visualizer interface, showing results for multiple term queries.

@davenquinn -- I'm planning to revisit the word2vec side of things this week. Could you take a look at the URL bit?
